vich_uploader:
    db_driver: orm

    mappings:
        product_image:
            uri_prefix: '%app.path.product_image%'
            upload_destination: '%kernel.project_dir%/public%app.path.product_image%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        product_category_image:
            uri_prefix: '%app.path.product_category_image%'
            upload_destination: '%kernel.project_dir%/public%app.path.product_category_image%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        product_brand_image:
            uri_prefix: '%app.path.product_brand_image%'
            upload_destination: '%kernel.project_dir%/public%app.path.product_brand_image%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        product_type_image:
            uri_prefix: '%app.path.product_type_image%'
            upload_destination: '%kernel.project_dir%/public%app.path.product_type_image%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
